DATABASE_URL_SUPERBASE="postgresql://postgres.prqmyvkdkbkfycrrrpdm:Radisson2026++@aws-1-eu-west-1.pooler.supabase.com:5432/postgres"
DATABASE_URL="postgresql://neondb_owner:npg_93mwOyNgQIHX@ep-calm-forest-abplqcg0-pooler.eu-west-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
ADMIN_PASSWORD="Raddison2025#"